### ISSUE TITLE
Move to voorhoede/fastatic-app

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede-labs/fastatic-app#3]
I think the app is stable enough by to move from voorhoede-labs to voorhoede organisation.

**Comment by petergoes** [comment]
Agreed, although I want to tackel two things before I think it is stabel.
1. I am strugeling with a rather nasty issue of building a version that can be downloaded and then still work. When I build the app on my machine, it works fine, but as soon as I put the .app on a server and download it, the actual `fastatic` module is never run
2. I am working with a `fastatic` module that is linked via `npm link`. IMHO we need to make a release of the `fastatic` module to consider this one stable and let people contribute to this app.

I do not know if the two issues are related though. I think not, but I'm not sure

**Comment by jbmoelker** [comment]
done.
